# Generated by Django 3.2.4 on 2021-06-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeBlog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
